name: RSpec

on:
  push:
    branches:
      - main

  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.8'
          - '3.2.2'

    env:
      RAILS_ENV: test
      CI: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
