name: Rubocop

on:
  push:
    branches:
      - main

  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8
          bundler-cache: true

      - name: Linter
        run: bundle exec rubocop
