name: Rubocop

on:
  push:
    branches:
      - main

  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.8'
          - '3.2.2'

    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Linter
        run: bundle exec rubocop
